syntax = "proto3";
package api;
option go_package = ".;api";

import "user.proto";
import "account_enum.proto";

message RechargeWay {
  bool google = 1;
}

message GlobalCfgArg {
  string channel = 1; // 渠道
}

// 全局配置
message GlobalCfgReply{
  User helper = 1; // 小助手 id:-1001
  User secretary = 2; // 小秘书 id:-1002
  User tipsHelper = 3; // 动态提示 id:-1003
  User customer = 4; // 客服 id:-1004
  int64 serverTime = 5; // 服务器当前时间
  //NobleConfig nobleCfg = 6; // 贵族相关配置
  bool videoCall = 7; // 是否开启视频通话
  RechargeWay rechargeWay = 8; // 充值方式
  int32 guildJumpType = 9; //公会页跳转方式 1:原生 2:h5
  bool checkRoot = 10; //是否检查用户设备root权限
  repeated PicConfig pic = 11; //服务端配置图片资源
  int64 msgExpiredDuration = 12; //消息超时时间 分钟
  int64 privateAlbumUpload = 13; //可上传私密相册阈值
  bool privateAlbumShow = 14; //是否展示私密相册
  repeated SystemLanguage languageList = 15; //语言列表
  repeated LogoutReasonList logoutReason = 16;//退出登录原因
  bool homeSelect = 17;//首页筛选展示
  string homeRank = 18;//首页排行榜展示
  bool sessionVoice = 19; //私聊音视频开关
  bool income = 20; // 是否显示收益入口开关
  bool reportPage = 21;//意见反馈入口开关
  bool helpPage = 22;;//帮助页入口开关
}

message PicConfig {
  int32 id = 1;
  string name = 2;
  string file = 3;
}

message SystemLanguage {
  string languageCode = 1;//语言标识
  string language = 2;//语言
}

message LogoutReasonList {
  LogoutReason reason = 1;
  string content = 2;
}